x = torch.tensor(7)  
(torch.__version__)  
x.ndim  
x.item()  
x = torch.tensor([7,7])  
x.shape  
x = torch.tensor([[1,2], [3,4]])  
x = torch.tensor([3,6,9], dtype = torch.float32)  
x = torch.rand(3, 4)  
x = torch.zeros(3,4)  
x = ones=torch.ones(3,4)  
x.dtype  
onetoten = torch.arange(start =0, end = 1000, step = 20)  
ten_zeros = torch.zeros_like(input = onetoten)  


### Pytorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.9.0+cpu


In [5]:
torch.cuda.is_available()

False

## Intro to Tensors

In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [14]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [31]:
MATRIX = torch.tensor([[1,2],
                     [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [32]:
MATRIX.ndim

2

In [33]:
MATRIX[0]

tensor([1, 2])

In [34]:
MATRIX.shape

torch.Size([2, 2])

In [55]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [56]:
TENSOR.ndim

3

In [57]:
TENSOR.shape

torch.Size([1, 3, 3])

# torch. size([No. of Matrices. no. of rows, no. of columns])

In [39]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
TENSOR[0][0]

tensor([1, 2, 3])

In [42]:
TENSOR[0][1]

tensor([4, 5, 6])

In [49]:
TENSOR[0][2]

tensor([7, 8, 9])

In [43]:
TENSOR[0][0][0]

tensor(1)

In [44]:
TENSOR[0][0][1]

tensor(2)

In [46]:
TENSOR[0][1][0]

tensor(4)

In [47]:
TENSOR[0][2][2]

tensor(9)

In [50]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,7],
                        [7,8,9,0]]])
TENSOR.shape

torch.Size([1, 3, 4])

In [52]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9],
                       [1,4,0]]])
TENSOR.shape

torch.Size([1, 4, 3])

In [53]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,7],
                        [7,8,9,0]],
                       [[1,2,3,4],
                        [4,5,6,7],
                        [7,8,9,0]]])
TENSOR.shape

torch.Size([2, 3, 4])

In [66]:
TENSOR = torch.tensor([[[[1,2,3,4],
                        [4,5,6,7],
                        [7,8,9,0]],
                       [[1,2,3,4],
                        [4,5,6,7],
                        [7,8,9,0]]]])
TENSOR.shape

torch.Size([1, 2, 3, 4])

In [67]:
x = torch.rand(3, 4)
print(x)

tensor([[0.3086, 0.3191, 0.9821, 0.1449],
        [0.0933, 0.7164, 0.9031, 0.7042],
        [0.3279, 0.7862, 0.7273, 0.3556]])


In [68]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
ones.dtype

torch.float32

In [71]:
onetoten = torch.arange(start =0, end = 1000, step = 20)
onetoten

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540,
        560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820,
        840, 860, 880, 900, 920, 940, 960, 980])

In [73]:
ten_zeros = torch.zeros_like(input = onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [81]:
int_32_tensor1 = torch.tensor([3,6,9], dtype = torch.float32)
int_32_tensor2 = torch.tensor([3,6,9], dtype = torch.float64)
int_64_tensor = int_32_tensor1 * int_32_tensor2
int_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [82]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6609, 0.8626, 0.3469, 0.3107],
        [0.8601, 0.6060, 0.5422, 0.3920],
        [0.2893, 0.1737, 0.2411, 0.4784]])

In [86]:
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu
