tensor = torch.from_numpy(array) =>  Numpy -> pytorch tensor  
y = tensor.numpy() => pytorch tensor-> Numpy  
torch.manual_seed(RANDOM_SEED) -> reproduce the same random numbers

In [21]:
import torch
import numpy as np

In [22]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [23]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
x[0][0]

tensor([1, 2, 3])

In [25]:
x[0][0][1]

tensor(2)

In [26]:
x[:,0,1]

tensor([2])

In [38]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [60]:
x[:,:,0:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [61]:
x[:,:,1:]

tensor([[[2, 3],
         [5, 6],
         [8, 9]]])

In [62]:
x[:,:,2:]

tensor([[[3],
         [6],
         [9]]])

In [59]:
x[:,:,:1]

tensor([[[1],
         [4],
         [7]]])

In [33]:
x[:,:,:2]

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [34]:
x[:,:,:3]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [72]:
x[:,:,0:1]

tensor([[[1],
         [4],
         [7]]])

In [70]:
x[:,:,1:2]

tensor([[[2],
         [5],
         [8]]])

In [35]:
x[:,:1,:]

tensor([[[1, 2, 3]]])

In [36]:
x[:,:2,:]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [37]:
x[:,:3,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [39]:
x[:1,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [51]:
y=x[:1,:,:]
y,y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
x[1:,:,:]

tensor([], size=(0, 3, 3), dtype=torch.int64)

In [73]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
array = array + 1 # it won't impact tensor values
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
x=torch.ones(7)
numpy_tensor = x.numpy()
x,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
A = torch.rand(3,4)
B = torch.rand(3,4)
A,B

(tensor([[0.5357, 0.6274, 0.6123, 0.9419],
         [0.0036, 0.2403, 0.6873, 0.6192],
         [0.9553, 0.8278, 0.2659, 0.2266]]),
 tensor([[0.6366, 0.1321, 0.1914, 0.2640],
         [0.4184, 0.5426, 0.4580, 0.7392],
         [0.8273, 0.4699, 0.2583, 0.8042]]))

In [81]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
A = torch.rand(3,4)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
B = torch.rand(3,4)
A,B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [99]:
x=[1,2,3,4,5,6,7,8,9,0]
x[8:]

[9, 0]

In [100]:
x[:8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [101]:
x[3:7]

[4, 5, 6, 7]