### Manipulation Tensors - Tensor Operation

    Addition
    Subtraction
    Multiplication - Element wise
    Division
    Matrix Multiplication

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [13]:
tensor*10

tensor([10, 20, 30])

In [14]:
tensor-20

tensor([-19, -18, -17])

In [15]:
tensor

tensor([1, 2, 3])

In [16]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [17]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [18]:
tensor*tensor

tensor([1, 4, 9])

In [33]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 316 μs


tensor(14)

In [29]:
%%time
value=0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.23 ms


In [36]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

In [37]:
tensor_A.mT

tensor([[1, 3, 5],
        [2, 4, 6]])

In [39]:
tensor_A.shape


torch.Size([3, 2])

In [40]:
tensor_A.mT.shape

torch.Size([2, 3])

In [46]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [44]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [45]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [48]:
y = torch.mean(x.type(torch.float32))
y, y.dtype

(tensor(45.), torch.float32)

In [50]:
y = x.type(torch.float32).mean()
y, y.dtype

(tensor(45.), torch.float32)

In [51]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [52]:
x.argmin()

tensor(0)

In [53]:
x.argmax()

tensor(9)

In [55]:
x=torch.arange(1.,10)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
x=torch.arange(1.,13)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [60]:
x_reshaped = x.reshape(3,4)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [62]:
x_reshaped = x.reshape(4,3)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [64]:
x=torch.arange(1.,10)
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
z[:,0]=5 # changing Z value reflect in x also like pointer 
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [79]:
x = torch.zeros(2, 1, 2, 1, 2)
x,x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [80]:
y = torch.squeeze(x)
y,y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [81]:
y = torch.squeeze(x, 0)
y,y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [82]:
y = torch.squeeze(x, 1)
y,y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [83]:
y = torch.squeeze(x, (1, 2, 3))
y,y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [84]:
y = torch.squeeze(x, 3)
y,y.size()

(tensor([[[[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]]]]),
 torch.Size([2, 1, 2, 2]))

In [85]:
x = torch.zeros(1, 2, 2, 1, 2)
x,x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]],
 
 
          [[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([1, 2, 2, 1, 2]))

In [86]:
y = torch.squeeze(x, 0)
y,y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))